payara/ecosystem-maven

payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/BundleMojo.java, payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/processor/ArtifactDeployProcessor.java
Probably a hacky fix, but I can't think of a better one short of rewriting the plugin to use the --outputUberjar flag. 
The maven plugin deploys by extracting Payara Micro, adding in all the right files, and then zipping it up again., and Payara Micro deploys by last modified date. This fix just changes the artifact's last modified date to be more recent than other dependencies.
=> PAYARA-2290 Payara Micro Maven Plugin Incorrect Deployment Order

payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/Configuration.java, payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/StopMojo.java
To avoid port collisions with the previously started instance if it takes too long to stop
=> MP-28 Wait for killed instance to shutdown before starting

payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/BundleMojo.java, payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/processor/ArtifactDeployProcessor.java, payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/processor/BaseProcessor.java
This changes lookup of main artifact file to fix behavior for points 1 and 2:
1. tries to get it from Maven API (works only if WAR built in the same lifecyle, e.g. with `mvn package payara-micro:bundle`)
2. tries to assemble the path from config in pom.xml (in case of 2 lifecycles, like `mvn package && mvn payara-micro:bundle`)
3. resorts to maven repository (works for example with `mvn clean payara-micro:bundle` if the artifact is in a maven repo already)
=> MP-29 Fix build without local repo

payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/StartMojo.java
Integration Tests using maven failsafe and the payara-mirco-plugin hung unexpectedly. Thread-Dumps indicated a lock at the JUL. Closing the BufferedReader solves the problem. This issue occurs under Windows only. 
Java 1.8.0_172, Payara Micro 5.183, Maven 3.5.4
=> Problem with Integration Test using maven failsafe

payara-micro-maven-archetype/src/main/resources/archetype-resources/pom.xml
This moves JDK version and web.xml options outside of the plugin declaration. Also removed the "endorsed dir" setting that isn't needed.
=> Simplified generated pom.xml

payara-micro-maven-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml, payara-micro-maven-archetype/src/main/resources/archetype-resources/pom.xml
At least Concurrency Utilities, JCA and JBatch specs are supported on Payara Micro.
I added JCache and Payara API as optional dependencies since JCache is not part of Java EE and Payara API is vendor specific.
https://github.com/payara/Payara/issues/2082 would help in maintining the list of specs updated.
=> Added additionally supported APIs

payara-micro-maven-plugin/pom.xml
Signatures are only required during plugin release, release-profile is the profile active during
release:perform
=> Only sign artifacts during release phase

payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/processor/MicroFetchProcessor.java
Transitive dependencies are not needed, and due to atypical types, they even fail when used with snapshot build like this:
````
[ERROR] Failed to execute goal fish.payara.maven.plugins:payara-micro-maven-plugin:1.0.3:start
(default-cli) on project sample-rest-client:
Couldn't download artifact: org.eclipse.aether.resolution.DependencyResolutionException:
Could not find artifact 
org.glassfish.main.jdbc:templates:distribution-fragment:5.192-SNAPSHOT
````
=> Do not fetch transitive dependencies of payara-micro

payara-micro-maven-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml, payara-micro-maven-archetype/src/main/resources/archetype-resources/pom.xml
Previously `""` was written as context path, which made applications accesible at `localhost:8080/""`.
=> Set default context path as root

payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/ReloadMojo.java, payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/StartMojo.java
This is a feature to deploy an exploded War without restarting the Payara Micro instance.
> An exploded war can be deployed to a Payara Micro instance just be specifying the path to the exploded war root directory on the --deploy command line or via the API. The exploded war can be redeployed by creating a file .reload in the root directory of the exploded war and updating its timestamp for example using touch .reload in a LINUX machine.
https://docs.payara.fish/documentation/payara-micro/deploying/deploy-cmd-line.html
=> ECOSYS-125 Payara Micro reload mojo in maven plugin

payara-micro-maven-plugin/pom.xml
Reverts payara/ecosystem-maven#140
Downgraded version as NetBeans IDE bundled with an older version of Maven build.
=> Revert "Bump maven-api.version from 3.3.9 to 3.6.3 in /payara-micro-maven-plugin"

payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/processor/BootCommandFileCopyProcessor.java, payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/processor/CustomFileCopyProcessor.java
If users provide a file to be bundled (i.e. pre-boot-commands.txt) it
should overwrite the bundled version of the file included by default
in Payara Micro.
Closes #148
=> Overwrite Bundled Files with User Provided Files

payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/StartMojo.java
The custom context path configured in the application property panel of  Apache NetBeans is passed via `-Dnetbeans.deploy.clientUrlPart="/my-app-context-path"` property to the command-line. So the handing of `netbeans.deploy.clientUrlPart` property is required in the Payara Micro Maven plugin alternative to `contextRoot` property.
=> FISH-607 Use netbeans.deploy.clientUrlPart property to set contextPath from Payara Micro Maven Plugin

payara-micro-maven-plugin/pom.xml, payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/AutoDeployHandler.java, payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/DevModeHandler.java, payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/DevMojo.java, payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/InvokerLoggerImpl.java, payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/ReloadMojo.java, payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/StartMojo.java
This pull request, linked to FISH-7893, introduces the AutoDeploy feature for the Payara Micro Maven plugin. The AutoDeploy feature enables automatic compilation and deployment of the application upon saving files within the project structure. The key commands and behaviors introduced are as follows:
To activate auto-deploy, use the following command:
````
mvn install payara-micro:start -DautoDeploy=true
````
Upon setting autoDeploy=true, the application will be automatically compiled and deployed whenever a file is saved within the project structure.
Utilizes Java's WatchService to monitor changes in source directories.
Listens for file modifications and initiates builds accordingly using Maven's Invoker.
Dynamically modifies Maven goals based on file modifications (e.g., cleans the …
=> FISH-7893 Payara Micro Maven plugin - Devmode - compile and deploy application on save operation

payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/processor/CustomFileCopyProcessor.java
Include `keystore.p12` in addition to `keystore.jks`.  JKS is deprecated, and Payara 6+ uses PKCS12 by default.
=> Include PKCS12 Keystore

payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/Configuration.java, payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/DevMojo.java, payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/LogUtils.java, payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/PropertiesUtils.java, payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/StartMojo.java
This pull request introduces the trimLog property to the Payara Micro Maven plugin. When enabled (default for dev mojo, disabled for start mojo), it refactors the log format for improved readability. The `trimLog` property can be disabled in `dev` mojo if Maven is started with `-X`.
- Added trimLogs property to plugin configuration.
- Implemented logic to adjust log format based on the value of trimLogs.
- Tested compatibility with both dev and start mojo.
```
[2024-01-18T17:22:14.559+0530] [] [INFO] [] [fish.payara.nucleus.hazelcast.HazelcastCore] [tid: _ThreadID=32 _ThreadName=RunLevelControllerThread-1705578730178] [timeMillis: 1705578734559] [levelValue: 800] JSR107 Default Cache Manager Bound to JNDI at payara/CacheManager
[2024-01-18T17:22:14.734+0530] [] [INFO] [NCLS-CORE-00101] …
```
=> FISH-8150 Micro Maven - Devmode - Refactor Payara Micro Log Format for Improved Readability

payara-micro-maven-plugin/pom.xml
Reverts payara/ecosystem-maven#276
=> Revert "Bump org.codehaus.plexus:plexus-utils from 3.4.2 to 4.0.0 in /payara-micro-maven-plugin" ad breaking org.twdata.maven:mojo-executor

payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/AutoDeployHandler.java, payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/DevMojo.java, payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/ReloadMojo.java, payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/StartMojo.java, payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/WebDriverFactory.java
This pull request enhances the Micro Maven plugin for Payara Micro by introducing a new configuration property, keepState. This property allows for the persistence of session state across multiple redeployments during the development process. By default, the `keepState` property is set to `false` for the `start` mojo and `true` for the `dev` mojo.
To validate this enhancement, a test servlet (NewServlet) has been created. The servlet utilizes the HttpSession to store and increment a session attribute ("count") with each request. The keepState property ensures that the session state is maintained across auto-reload processes, providing a seamless development experience for session-dependent functionalities.
https://github.com/payara/Payara-Enterprise/pull/1067
Utilize the provided …
=> FISH-8152 Micro Maven - Devmode - Store session state

payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/AutoDeployHandler.java, payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/Configuration.java, payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/DevMojo.java, payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/LogUtils.java, payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/Option.java, payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/PropertiesUtils.java, payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/ReloadMojo.java, payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/StartMojo.java, payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/WebDriverFactory.java
This pull request addresses the challenges faced in the Payara Micro Maven Plugin's dev mode, specifically when deployment fails after a successful build. The proposed solution introduces a fail-safe mechanism that involves the addition of a `dev-mode` flag for persistent deployment.
Added a new dev mode flag that can be passed to Payara Micro. This flag instructs Payara Micro to persistently monitor for changes after the failure of application deployment.
Implemented test cases to cover various scenarios:
- Payara Micro instance started, and application deployed:
- Compilation/Build failed
- Build successful but application deployment failed
- The Payara Micro instance started, but the application was not deployed due to deployment failure:
- Compilation/Build failed
- Build successful …
=> FISH-8259 Improve Dev Mode Fail-Safe Mechanism

.github/dependabot.yml, payara-cloud-maven-plugin/pom.xml, payara-cloud-maven-plugin/src/main/java/fish/payara/maven/plugins/cloud/BasePayaraMojo.java, payara-cloud-maven-plugin/src/main/java/fish/payara/maven/plugins/cloud/Configuration.java, payara-cloud-maven-plugin/src/main/java/fish/payara/maven/plugins/cloud/LoginMojo.java, payara-micro-maven-archetype/pom.xml
This PR adds initial features to authenticate devices for Cloud operation.
- To test it build the PR Ecosystem-Cloud (https://github.com/payara/ecosystem-cloud/pull/1) and this PR (https://github.com/payara/ecosystem-maven/pull/324).
-  Run the following command and it will open the browser to follow the auth process.
`mvn fish.payara.maven.plugins:payara-cloud-maven-plugin:1.0-SNAPSHOT:login`
=> FISH-7898 Payara Maven plugin - Authenticate Payara Cloud

payara-cloud-maven-plugin/pom.xml, payara-cloud-maven-plugin/src/main/java/fish/payara/maven/plugins/cloud/BasePayaraMojo.java, payara-cloud-maven-plugin/src/main/java/fish/payara/maven/plugins/cloud/Configuration.java, payara-cloud-maven-plugin/src/main/java/fish/payara/maven/plugins/cloud/DeployMojo.java, payara-cloud-maven-plugin/src/main/java/fish/payara/maven/plugins/cloud/LoginMojo.java, payara-cloud-maven-plugin/src/main/java/fish/payara/maven/plugins/cloud/UndeployMojo.java
This PR adds initial features to deploy/undeploy applications to Payara Cloud:
- To test it build the PR Ecosystem-Cloud (https://github.com/payara/ecosystem-cloud/pull/2) and this PR.
-  Run the following command and it will open the browser to follow the auth process and deploy application.
`mvn fish.payara.maven.plugins:payara-cloud-maven-plugin:1.0-SNAPSHOT:deploy`
=> FISH-7900 Payara Maven plugin - Deploy/Undeploy application to Payara Cloud

payara-micro-maven-plugin/pom.xml, payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/PayaraMicroVersionSelector.java, payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/StartMojo.java
This PR introduces a new feature that intelligently selects the appropriate Payara Micro version based on the Jakarta EE version used in the Maven project dependencies. If no matching Jakarta EE version is found, it defaults to the latest Payara Micro version available.
1. **Retrieve Jakarta EE Version:**
- Fetches the Jakarta EE version from the project dependencies by checking for the `jakarta.platform` group ID.
2. **Determine Jakarta EE Major Version:**
- Extracts the major version (e.g., 8, 9, 10, 11) from the Jakarta EE version.
3. **Fetch Payara Micro Version Metadata:**
- Retrieves Payara Micro version metadata from the Maven repository via the `maven-metadata.xml` file.
4. **Version Matching Logic:**
- Iterates over the available Payara Micro versions (in reverse order) to select …
=> FISH-9509 Payara Micro Maven plugin auto select Payara Micro version

payara-server-maven-plugin/pom.xml, payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/BasePayaraMojo.java, payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/BaseProcessor.java, payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/Configuration.java, payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/PayaraServerInstance.java, payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/ServerFetchProcessor.java, payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/ServerMojo.java, payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/StartMojo.java, payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/parser/JDKVersion.java, payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/parser/JvmConfigReader.java, payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/parser/JvmOption.java, payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/parser/PortReader.java, payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/utils/JavaUtils.java, payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/utils/ServerUtils.java, payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/utils/StringUtils.java
This PR adds the capability to start and stop a local Payara Server instance using the **Payara Server Maven Plugin**. It simplifies the server lifecycle management by enabling developers to control the server directly through Maven commands.
- `payara-server:start` - Starts the local Payara Server.
- Ctrl + C to stop the running Payara Server.
Add the following plugin configuration to your project's pom.xml file:
```
<build>
<plugins>
<plugin>
<artifactId>payara-server-maven-plugin</artifactId>
<version>1.0.0-Alpha1</version>
</plugin>
</plugins>
</build>
```
To start the server:
```bash
mvn payara-server:start -DpayaraVersion=6.2024.12
```
=> FISH-10239 Start and Stop Local Payara Server using Payara Server Maven Plugin

payara-server-maven-plugin/pom.xml, payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/Command.java, payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/PayaraServerInstance.java, payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/Response.java, payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/ServerManager.java, payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/ServerMojo.java, payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/StartMojo.java, payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/utils/ServerUtils.java
This PR adds the capability to deploy application to a local Payara Server instance using the **Payara Server Maven Plugin**. It simplifies the server lifecycle management by enabling developers to control the server directly through Maven commands.
- **Exploded Deployment Support**: Added a new `exploded` parameter to control whether the application is deployed as an exploded WAR or a packaged WAR.  
- If `-Dexploded=true` is set, the application will be deployed in exploded form.  
- By default (`exploded=false`), the WAR file will be deployed as a packaged archive.  
Add the following plugin configuration to your project's pom.xml file:
```
<build>
<plugins>
<plugin>
<artifactId>payara-server-maven-plugin</artifactId> …
```
=> FISH-10240 Deploy application to Payara Server using Payara Server Maven Plugin

payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/ServerMojo.java, payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/StartMojo.java, payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/manager/InstanceManager.java, payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/manager/LocalInstanceManager.java, payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/manager/PayaraServerInstance.java, payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/manager/PayaraServerLocalInstance.java, payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/manager/PayaraServerRemoteInstance.java, payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/manager/RemoteInstanceManager.java, payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/response/JsonResponse.java, payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/response/PlainResponse.java, payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/response/Response.java
This PR adds the capability to deploy application to a remote Payara Server instance using the **Payara Server Maven Plugin**. It simplifies the server lifecycle management by enabling developers to control the app deployment to remote server directly through Maven commands.
Make sure remote server is running:
```bash
bin$ ./asadmin start-domain
bin$ ./asadmin change-admin-password
bin$ ./asadmin enable-secure-admin
bin$ ./asadmin restart-domain
bin$ hostname -I
172.25.157.198
```
Add the following plugin configuration to your project's pom.xml file:
```
<build>
<plugins>
<plugin>
<artifactId>payara-server-maven-plugin</artifactId>
<version>1.0.0-Alpha1</version>
</plugin>
</plugins>
</build>
```
To deploy the application to the remote server: …
=> FISH-10462 Remote Server instance support in Payara Server Maven Plugin

payara-maven-plugins-common/pom.xml, payara-maven-plugins-common/src/main/java/fish/payara/maven/plugins/LogUtils.java, payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/StartMojo.java, payara-server-maven-plugin/pom.xml, payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/Command.java, payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/DevMojo.java, payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/Option.java, payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/ServerAutoDeployHandler.java, payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/StartMojo.java, payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/manager/InstanceManager.java, payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/manager/LocalInstanceManager.java
This pull request enhances the Payara Server Maven plugin for Payara Server by introducing a new `dev` mode goal.
To test it, start a Payara Server instance and use the following command to activate dev mode:
```
mvn install payara-server:dev 
```
Which is equivalent to activating auto-deploy with hot-deploy, use the following command:
````
mvn install payara-server:start -DautoDeploy=true -DliveReload=true -DdeployWar=true -Dexploded=true
````
Modify the source code, and it should automatically deploy and refresh the browser page.
=============================================
This pull request also introduces support for additional configuration options:
**Default:** None  
Defines a list of command-line options that will be passed to the Java executable. Options can be defined as …
=> FISH-10241/FISH-10425 Dev mode and Config support in Payara Server Maven Plugin

payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/manager/LocalInstanceManager.java
Added the payara-server-maven-plugin to the pom.xml:
```
<plugin>
<artifactId>payara-server-maven-plugin</artifactId>
<version>1.0.0-Alpha1</version>
</plugin>
```
Run the application using:
```
mvn install payara-server:start
```
Ensure the application path (i.e., project directory) has spaces in it to verify correct behavior.
=> FISH-10856 Payara Server Start Operation Fails if Path Contains Spaces

payara-server-maven-plugin/pom.xml, payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/DevMojo.java, payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/StartMojo.java, payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/manager/InstanceManager.java, payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/manager/LocalInstanceManager.java, payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/manager/PayaraServerLocalInstance.java, payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/response/JsonResponse.java
This PR integrate with AI Agent and describes the environment variables and system properties available for configuring the Payara AI Agent.
The configuration values can be provided **either** via **environment variables** or **system properties**.  
---
| Environment Variable              | System Property               | Description |
|:-----------------------------------|:-------------------------------|:------------|
| `PAYARA_AI_API_KEY`                | `payara.ai.api.key`            | API Key for authentication with the AI provider. |
| `PAYARA_AI_PROVIDER_LOCATION`      | `payara.ai.provider.location`  | Base URL or endpoint of the AI provider. |
| `PAYARA_AI_PROVIDER`               | `payara.ai.provider`           | Name or identifier of the AI provider (e.g., `OpenAI`, …
=> FISH-10921 Payara AI Agent integration

payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/StartMojo.java, payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/manager/InstanceManager.java, payara-server-maven-plugin/src/main/java/fish/payara/maven/plugins/server/manager/PayaraServerLocalInstance.java
This PR sets up and verifies usage of the `payara-server-maven-plugin` with secure admin enabled in Payara Server.
1. **Start the Payara Domain**
```bash
asadmin start-domain domain1
```
2. **Change Admin Password**
Run the following command and update the password when prompted:
```bash
asadmin change-admin-password
```
3. **Enable Secure Admin**
```bash
asadmin enable-secure-admin
```
4. **Stop the Domain**
```bash
asadmin stop-domain domain1
```
---
```bash
mvn package fish.payara.maven.plugins:payara-server-maven-plugin:1.0.0-Alpha3-SNAPSHOT:dev \
-Dpayara.server.path="D:\Software\payara-web-6.2025.7\payara6" \
-Dpayara.admin.user=admin \
-Dpayara.admin.password=admin
```
---
Successful connection to Payara Server with secure admin enabled, allowing deployment using the Maven plugin.
=> FISH-11608 Authentication error message handling
