README.md
payara-micro-maven-plugin/pom.xml
payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/BasePayaraMojo.java
payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/Option.java
payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/StartMojo.java
payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/StopMojo.java

PAYARA-1152-Create-maven-plugin-for-packaging-a-Payara-Micro-jar

---

payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/StartMojo.java

Fixes #6 by failing fast with a clear message.

Added some validation checks

---

payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/BundleMojo.java
payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/processor/ArtifactDeployProcessor.java

Adds contextRoot option for autodeployed app.
The second commit changes the default context root to `ROOT` meaning `/` and adds option to revert to older behavior.

PAYARA-2156 Config improvements

---

payara-micro-maven-archetype/src/main/resources/archetype-resources/pom.xml

Signed-off-by: Gaurav Gupta <gaurav.gupta.jc@gmail.com>

MP-11 payara-micro-maven-plugin version upgrade

---

payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/BundleMojo.java
payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/processor/ArtifactDeployProcessor.java
payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/processor/BaseProcessor.java

Fixes null pointer when bundle goal is executed, see https://groups.google.com/forum/#!topic/payara-forum/nO0ewuoHD2Y
Also fixes setting the current timestamp when the artifact file is renamed in the bundled file.

Fixes null pointer. Fixes setting timestamp when contextRoot != null

---

.gitignore
payara-micro-maven-plugin/pom.xml

Tested with `release:prepare release:perform` locally, gpg key needs to be in user settings.

MP-59 Use Maven Release Plugin

---

payara-micro-maven-plugin/README.md
payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/BundleMojo.java
payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/processor/CustomFileCopyProcessor.java

See https://github.com/payara/ecosystem-maven/issues/103

MP-75 Copy metrics.xml & hazelcast-config.xml config files to MICRO-INF domain folder

---

payara-micro-maven-plugin/README.md
payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/BundleMojo.java
payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/StartMojo.java

ECOSYS-122 Upgrade dependencies in payara-micro-maven-plugin to latest version

---

payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/ReloadMojo.java
payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/StartMojo.java

https://github.com/payara/Payara/pull/5143
https://github.com/payara/ecosystem-vscode-plugin/pull/71

FISH-1076 Hot Deploy args added to Payara Micro Mojos

---

payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/AutoDeployHandler.java
payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/StartMojo.java

This PR introduces restart functionality to Maven-DevMode for Payara Micro, enabling a seamless instance restart upon modifications to the boot command file. Enhances the development experience by offering a quick server restart option for improved development efficiency.
To test this feature:
Create a new Maven project or use an existing one with the required project structure (e.g., standard Maven web project structure).
Inside the `<build><plugins>` section of your pom.xml, add the Payara Micro Maven Plugin configuration provided:
~~~~
<project>
<build>
<plugins>
<plugin>
<artifactId>payara-micro-maven-plugin</artifactId>
<version>2.0</version>
<configuration>
<payaraVersion>${version.payara}</payaraVersion>
<deployWar>false</deployWar> …

FISH-8116 Maven-DevMode: Restart Micro instead of reload on modifying the boot command file

---

payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/AutoDeployHandler.java
payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/ReloadMojo.java
payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/Source.java

To activate auto-deploy with hot-deploy, use the following command:
````
mvn install payara-micro:start -DautoDeploy=true -DhotDeploy=true
````
Upon setting autoDeploy=true, the application will be automatically compiled and deployed whenever a file is saved within the project structure.

FISH-7894 Payara Micro Maven plugin - Devmode - compile and hot deploy application on save operation

---

payara-micro-maven-plugin/pom.xml
payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/AutoDeployHandler.java
payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/Configuration.java
payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/DevMojo.java
payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/Source.java
payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/StartMojo.java
payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/WebDriverFactory.java

Introducing the LiveReload feature in the Payara Micro Maven plugin's Dev Mode configuration enhances the development experience by automatically refreshing the browser upon redeployment. The new `liveReload` property, when set to `true`, triggers a browser refresh, ensuring developers have an up-to-date view of their application after each redeployment.
To activate dev mode, use the following command:
````
mvn install payara-micro:dev
````
Which is equivalent to activating auto-deploy with hot-deploy, use the following command:
````
mvn install payara-micro:start -DautoDeploy=true -DliveReload=true -DdeployWar=true -Dexploded=true
````
The addition of a `liveReload` property within the Payara Micro Maven plugin configuration allows users to enable or disable automatic browser refresh on …

FISH-8139 Micro Maven - Devmode - LiveReload browser

---

payara-cloud-maven-plugin/pom.xml
payara-maven-plugins-common/pom.xml

https://github.com/payara/ecosystem-cloud/pull/4

FISH-8659 Release Payara Cloud Maven Plugin 1.0-Alpha1

---

payara-cloud-maven-plugin/pom.xml
payara-cloud-maven-plugin/src/main/java/fish/payara/maven/plugins/cloud/BasePayaraMojo.java
payara-cloud-maven-plugin/src/main/java/fish/payara/maven/plugins/cloud/CloudMavenOutput.java
payara-cloud-maven-plugin/src/main/java/fish/payara/maven/plugins/cloud/LoginMojo.java
payara-maven-plugins-common/pom.xml

https://github.com/payara/ecosystem-cloud/pull/7

FISH-8770 Improve logging format and remove javax.activation.DataSource warning in Payara Cloud Maven Plugin

---

payara-maven-plugins-common/pom.xml
payara-maven-plugins-common/src/main/java/fish/payara/maven/plugins/AutoDeployHandler.java
payara-maven-plugins-common/src/main/java/fish/payara/maven/plugins/Configuration.java
payara-maven-plugins-common/src/main/java/fish/payara/maven/plugins/Source.java
payara-micro-maven-plugin/nbactions.xml
payara-micro-maven-plugin/pom.xml

This PR optimizes the AutoDeploy features:
- Include profile information
- Uses 'process-resources' to copy resources from the custom directory
- Handles and filters temporary files generated by IntelliJ with `.java~` extension.
- Handles IDEs related files from `.settings`, `.vscode`, `.idea`, `..classpath`, `project`, and `nb-configuration.xml`.

FISH-8555 Micro Plugin - Petclinic app fails to reload after a modification

---

payara-server-maven-plugin/pom.xml

Increment version for Development iteration

Increment Version Numbers 1.0.0-Alpha2-SNAPSHOT

---

payara-maven-plugins-common/pom.xml

Increment version for Development iteration

Increment Version Numbers 1.0.0-Alpha6-SNAPSHOT

---

payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/ReloadMojo.java

See https://payara.atlassian.net/browse/FISH-9696 for details.

FISH-9696 Fixes "No injectable constructor for type ReloadMojo"

---

payara-server-maven-plugin/pom.xml

Release version numbers 1.0.0-Alpha3

---

payara-server-maven-plugin/pom.xml

Increment version for Development iteration

Increment Version Numbers 1.0.0-Alpha4-SNAPSHOT

---

payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/BasePayaraMojo.java
payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/BundleMojo.java
payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/ReloadMojo.java
payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/StartMojo.java
payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/StopMojo.java

This PR sets each primitive parameter using system properties that start with 'payara.' and corresponding environment variables. It also adds a console warning for deprecated parameters along with guidance on migrating to the new parameters.

FISH-11747 Prefix Params with Payara

---

payara-micro-maven-plugin/pom.xml

Release version numbers 2.5.1
